server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:erp;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

logging:
  level:
    root: INFO